#!/usr/bin/env Rscript

# -----------------------------------------------------------------------------
# Figure 6B plotting script
#
# Purpose:
# Recreate the Bacteroidaceae substrate-diversity combined panel (tree +
# substrate bubblemap + substrate-count barplot + substrate-origin tiles).
#
# Inputs:
# - data/figure6/cgc_data.csv (generated by 00_generate_cgc_data.R)
# - data/gtdb/bac120_taxonomy_r226.tsv
# - data/gtdb/bac120_r226.tree
#
# Output:
# - results/figure6/Fig6A.pdf
# -----------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ape)
  library(ggtree)
  library(aplot)
})

# -----------------------------------------------------------------------------
# 1) Load CGC table and GTDB references
# -----------------------------------------------------------------------------

message("Loading inputs...")
# Gene-level CGC table produced by script 01
if (!file.exists("data/figure6/cgc_data.csv")) {
  source("figure6_scripts/00_generate_cgc_data.R")
}
cgc_data <- read_csv("data/figure6/cgc_data.csv", show_col_types = FALSE)

# Map sentence-case CSV headers to internal names used by plotting code
cgc_data <- cgc_data %>%
  rename(
    mag = `Mag`,
    `CGC#` = `Cgc#`,
    `Gene Type` = `Gene type`,
    `Gene Annotation` = `Gene annotation`,
    `Contig ID` = `Contig id`,
    `Gene Start` = `Gene start`,
    `Gene Stop` = `Gene stop`,
    `Gene Strand` = `Gene strand`,
    cazy_type = `Cazy type`,
    has_signalp_cgc = `Has signalp cgc`,
    has_signalp_gene = `Has signalp gene`,
    domain = `Domain`,
    phylum = `Phylum`,
    class = `Class`,
    order = `Order`,
    family = `Family`,
    genus = `Genus`,
    species = `Species`,
    Contig_N50 = `Contig n50`,
    Genome_Size = `Genome size`
  )

# GTDB taxonomy table used to annotate representative genomes
bac120_taxonomy <- read_delim(
  "data/gtdb/bac120_taxonomy_r226.tsv",
  col_names = FALSE,
  delim = "\t",
  show_col_types = FALSE
) %>%
  rename(genome = X1, taxonomy = X2) %>%
  separate(
    taxonomy,
    into = c("domain", "phylum", "class", "order", "family", "genus", "species"),
    sep = ";",
    fill = "right",
    remove = FALSE
  ) %>%
  mutate(across(c(domain, phylum, class, order, family, genus, species), ~ sub("^[a-z]__", "", .))) %>%
  mutate(
      # Keep family naming harmonized with the manuscript analysis
    family = case_when(
      str_detect(genus, "revotella") ~ "Prevotellaceae",
      TRUE ~ family
    )
  )

# Reference GTDB bac120 phylogeny (release 226)
bac120_tree <- read.tree("data/gtdb/bac120_r226.tree")

# -----------------------------------------------------------------------------
# 2) Build Bacteroidaceae species tree and tip ordering
# -----------------------------------------------------------------------------

message("Building Bacteroidaceae species tree...")
# Species set of high-quality Bacteroidaceae MAGs used in this section
bacteroidaceae_spp <- cgc_data %>%
  filter(
    Completeness >= 90,
    Contamination <= 10,
    Contig_N50 >= 50000,
    family == "Bacteroidaceae",
    species != ""
  ) %>%
  pull(species) %>%
  unique()

# Key linking each species to one representative GTDB genome label on the tree
bacteroidaceae_genomes_key <- bac120_taxonomy %>%
  filter(species %in% bacteroidaceae_spp, genome %in% bac120_tree$tip.label) %>%
  group_by(species) %>%
  slice_sample(n = 1) %>%
  ungroup()

# Species-subset tree for the left panel of the combined figure
bacteroidaceae_tree <- keep.tip(bac120_tree, bacteroidaceae_genomes_key$genome)

# Base tree object with species labels for panel alignment
bacteroidaceae_tree_plot <- ggtree(bacteroidaceae_tree) %<+% bacteroidaceae_genomes_key
#bacteroidaceae_tree_plot <- bacteroidaceae_tree_plot + # UNCOMMENT THIS LINE IF YOU WANT TO SEE THE TIP LABELS
#  geom_tiplab(aes(label = species), size = 3, align = TRUE) # UNCOMMENT THIS LINE IF YOU WANT TO SEE THE TIP LABELS

# y-axis ordering extracted from tree coordinates
bacteroidaceae_tip_order <- bacteroidaceae_tree_plot$data %>%
  filter(isTip) %>%
  arrange(y) %>%
  pull(label)

# -----------------------------------------------------------------------------
# 3) Recreate PUL substrate filtering used for combined_plot
# -----------------------------------------------------------------------------

message("Preparing PUL substrate diversity data...")

# SusC proxy: TCDB 1.B.14 annotation within CGCs
# Table of MAG/CGC combinations containing a susC-like transporter
susc_data <- cgc_data %>%
  filter(
    family == "Bacteroidaceae",
    species != "",
    str_detect(`Gene Annotation`, "1.B.14")
  ) %>%
  select(mag, `CGC#`) %>%
  distinct() %>%
  mutate(susc = TRUE)

# Pull one substrate annotation per MAG/CGC from cgc_data
# Substrate annotation table filtered to susC-positive CGCs
compiled_puls <- cgc_data %>%
  distinct(mag, `CGC#`, `Predicted substrate`) %>%
  rename(substrate = `Predicted substrate`) %>%
  left_join(susc_data, by = c("mag", "CGC#")) %>%
  filter(susc == TRUE)

# Keep only signal-positive digestive CGCs in Bacteroidaceae and summarize
# pul_data = per-genome/per-substrate median number of qualifying CGCs
pul_data <- cgc_data %>%
  filter(
    has_signalp_gene,
    family == "Bacteroidaceae",
    species != ""
  ) %>%
  select(mag, `CGC#`, species) %>%
  distinct() %>%
  left_join(compiled_puls, by = c("mag", "CGC#")) %>%
  filter(!is.na(substrate), !str_detect(substrate, "X|synthesis")) %>%
  left_join(bacteroidaceae_genomes_key %>% select(species, genome), by = "species") %>%
  distinct(mag, `CGC#`, .keep_all = TRUE) %>%
  mutate(substrate = str_replace(substrate, "hostglycan", "host glycan")) %>%
  group_by(mag, genome, species, substrate) %>%
  summarise(n_cgcs = n_distinct(`CGC#`), .groups = "drop") %>%
  group_by(genome, species, substrate) %>%
  summarise(median_cgcs = median(n_cgcs, na.rm = TRUE), .groups = "drop")

# -----------------------------------------------------------------------------
# 4) Define glycan ordering/origin metadata for plotting
# -----------------------------------------------------------------------------

plantcellwall_glycans <- c(
  "pectin", "arabinoxylan", "xyloglucan", "arabinogalactan", "galactomannan",
  "glucomannan", "alpha-mannan", "beta-mannan", "xylan", "arabinan",
  "galactan", "alpha-galactan", "beta-galactan"
)
plantstorage_glycans <- c("starch", "beta-glucan", "alpha-glucan", "fructan")
marinealgae_glycans <- c("carrageenan", "alginate", "agarose")
hostanimal_glycans <- c("host glycan", "mucin", "glycosaminoglycan", "human milk oligosaccharide")
microbial_glycans <- c("capsule polysaccharide degradation", "chitin")
glycan_order <- c(
  plantcellwall_glycans,
  plantstorage_glycans,
  marinealgae_glycans,
  hostanimal_glycans,
  microbial_glycans
)

# Enforce fixed substrate display order from manuscript
pul_data <- pul_data %>%
  filter(substrate %in% glycan_order) %>%
  mutate(substrate = factor(substrate, levels = glycan_order))

# Look-up table for substrate origin track at bottom of panel
substrate_origin <- data.frame(
  substrate = c(plantcellwall_glycans, plantstorage_glycans, marinealgae_glycans, hostanimal_glycans, microbial_glycans),
  origin = c(
    rep("Plant cell wall", length(plantcellwall_glycans)),
    rep("Plant storage", length(plantstorage_glycans)),
    rep("Marine algae", length(marinealgae_glycans)),
    rep("Host/animal", length(hostanimal_glycans)),
    rep("Microbial", length(microbial_glycans))
  )
)

# Color map for substrate origins
origin_colors <- c(
  "Plant cell wall" = "#99ce91",
  "Plant storage" = "#ba8e67",
  "Marine algae" = "#88edc4",
  "Host/animal" = "#f5c4c4",
  "Microbial" = "#c9b8e0"
)

substrate_origin$substrate <- factor(substrate_origin$substrate, levels = glycan_order)

# -----------------------------------------------------------------------------
# 5) Build and assemble figure panels
# -----------------------------------------------------------------------------

message("Building combined_plot...")

# Main panel: bubblemap of median CGC counts per substrate/species
substrate_bubblemap <- ggplot(
  pul_data,
  aes(x = substrate, y = genome, size = median_cgcs, color = median_cgcs)
) +
  geom_point(alpha = 0.8) +
  scale_size_continuous(name = "Median CGCs") +
  scale_color_viridis_c(name = "Median CGCs", direction = -1) +
  scale_y_discrete(limits = bacteroidaceae_tip_order) +
  theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank()
  )

# Bottom strip: substrate origin classes
origin_tile_plot <- ggplot(substrate_origin, aes(x = substrate, y = 1, fill = origin)) +
  geom_tile(height = 0.1) +
  scale_fill_manual(values = origin_colors, name = "Glycan origin") +
  scale_x_discrete(position = "bottom") +
  scale_y_continuous(expand = c(0, 0)) +
  theme_minimal(base_size = 10) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right"
  ) +
  labs(x = "Glycan substrate")

# Right panel: total number of substrates per species/genome
# Per-genome count of distinct predicted substrates
substrate_count_data <- pul_data %>%
  group_by(genome, species) %>%
  summarise(n_substrates = n_distinct(substrate), .groups = "drop")

# Horizontal bar panel aligned to tree tip order
substrate_count_plot <- ggplot(substrate_count_data, aes(x = n_substrates, y = genome)) +
  geom_col(fill = "gray60", alpha = 0.7) +
  scale_y_discrete(limits = bacteroidaceae_tip_order) +
  scale_x_continuous(breaks = c(0, 10, 20)) +
  theme_minimal(base_size = 10) +
  theme(
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  labs(x = "Substrates")

# Assemble panels in the same geometry used in the qmd analysis
combined_plot <- substrate_bubblemap %>%
  insert_left(bacteroidaceae_tree_plot, width = 0.2) %>%
  insert_right(substrate_count_plot, width = 0.15) %>%
  insert_bottom(origin_tile_plot, height = 0.02)

# -----------------------------------------------------------------------------
# 6) Save output
# -----------------------------------------------------------------------------

if (!dir.exists("results/figure6")) {
  dir.create("results/figure6", recursive = TRUE)
}

ggsave(
  filename = "results/figure6/Fig6A.pdf",
  plot = combined_plot,
  height = 5,
  width = 8
)

message("Saved: results/figure6/Fig6A.pdf")
