#!/usr/bin/env Rscript

# -----------------------------------------------------------------------------
# Figure 6B plotting script
#
# Purpose:
# Recreate the family-level tree-aligned distribution plot of
# signal-peptide digestive CGCs per MAG.
#
# Inputs:
# - data/figure6/cgc_data.csv (generated by 00_generate_cgc_data.R)
# - data/gtdb/bac120_taxonomy_r226.tsv
# - data/gtdb/bac120_r226.tree
#
# Output:
# - results/figure6/Fig6B.pdf
# -----------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ape)
  library(ggtree)
  library(aplot)
})

# -----------------------------------------------------------------------------
# 1) Load CGC table and GTDB references
# -----------------------------------------------------------------------------

message("Loading inputs...")
# Gene-level CGC data table produced by script 01
if (!file.exists("data/figure6/cgc_data.csv")) {
  source("figure6_scripts/00_generate_cgc_data.R")
}
cgc_data <- read_csv("data/figure6/cgc_data.csv", show_col_types = FALSE)

# Map sentence-case CSV headers to internal names used by plotting code
cgc_data <- cgc_data %>%
  rename(
    mag = `Mag`,
    `CGC#` = `Cgc#`,
    `Gene Type` = `Gene type`,
    `Gene Annotation` = `Gene annotation`,
    `Contig ID` = `Contig id`,
    `Gene Start` = `Gene start`,
    `Gene Stop` = `Gene stop`,
    `Gene Strand` = `Gene strand`,
    cazy_type = `Cazy type`,
    has_signalp_cgc = `Has signalp cgc`,
    has_signalp_gene = `Has signalp gene`,
    domain = `Domain`,
    phylum = `Phylum`,
    class = `Class`,
    order = `Order`,
    family = `Family`,
    genus = `Genus`,
    species = `Species`,
    Contig_N50 = `Contig n50`,
    Genome_Size = `Genome size`
  )

# GTDB taxonomy table used to map representative genomes to taxonomic labels
bac120_taxonomy <- read_delim(
  "data/gtdb/bac120_taxonomy_r226.tsv",
  col_names = FALSE,
  delim = "\t",
  show_col_types = FALSE
) %>%
  rename(genome = X1, taxonomy = X2) %>%
  separate(
    taxonomy,
    into = c("domain", "phylum", "class", "order", "family", "genus", "species"),
    sep = ";",
    fill = "right",
    remove = FALSE
  ) %>%
  mutate(across(c(domain, phylum, class, order, family, genus, species), ~ sub("^[a-z]__", "", .))) %>%
  mutate(
      # Keep family naming consistent with manuscript taxonomy conventions
    family = case_when(
      str_detect(genus, "revotella") ~ "Prevotellaceae",
      TRUE ~ family
    )
  )

# Reference GTDB bac120 phylogeny (release 226)
bac120_tree <- read.tree("data/gtdb/bac120_r226.tree")

# -----------------------------------------------------------------------------
# 2) Reconstruct MAG-level summary used for Figure 6A
# -----------------------------------------------------------------------------

message("Reconstructing MAG summary for signalp CGCs...")
# MAG-level summary table used for family-distribution plotting
mag_cazy_summary <- cgc_data %>%
  group_by(mag) %>%
  summarise(
    # Count CGCs per MAG that contain >=1 signal-positive digestive CAZyme
    n_CGCs_signalp = n_distinct(`CGC#`[has_signalp_cgc]),
    # Carry MAG-level taxonomy/QC fields forward
    domain = first(na.omit(domain)),
    phylum = first(na.omit(phylum)),
    class = first(na.omit(class)),
    order = first(na.omit(order)),
    family = first(na.omit(family)),
    genus = first(na.omit(genus)),
    species = first(na.omit(species)),
    Completeness = first(na.omit(Completeness)),
    Contamination = first(na.omit(Contamination)),
    Contig_N50 = first(na.omit(Contig_N50)),
    Genome_Size = first(na.omit(Genome_Size)),
    .groups = "drop"
  )

# Get family labels of of NC MAGs
families <- mag_cazy_summary %>%
  filter(
    Contamination <= 10,
    Completeness >= 90,
    Contig_N50 >= 50000,
    family != "UBA932"
  ) %>%
  pull(family) %>%
  unique()

# Map each target family to one representative genome present in the GTDB tree
family_genomes_key <- bac120_taxonomy %>%
  filter(family %in% families, genome %in% bac120_tree$tip.label) %>%
  group_by(family) %>%
  slice_sample(n = 1) %>%
  ungroup()

# Family-subset tree used in the left panel
family_tree <- keep.tip(bac120_tree, family_genomes_key$genome)

# Base tree object with family labels for alignment with percentile panel
family_tree_plot <- ggtree(family_tree)
#family_tree_plot <- family_tree_plot %<+% family_genomes_key + # UNCOMMENT THIS LINE IF YOU WANT TO SEE THE TIP LABELS
#  geom_tiplab(aes(label = family), size = 3, align = TRUE) # UNCOMMENT THIS LINE IF YOU WANT TO SEE THE TIP LABELS

# Join each MAG to representative family genome label used in the GTDB tree
plot_data <- mag_cazy_summary %>%
  left_join(family_genomes_key %>% select(family, genome), by = "family")

# -----------------------------------------------------------------------------
# 3) Helper: percentile-range panel aligned to tree tip order
# -----------------------------------------------------------------------------

make_percentile_plot <- function(summary_data, variable, tip_order, phylum_col = "phylum", genome_col = "genome", dot_color = "black", line_color = "gray50") {
  var_sym <- rlang::ensym(variable)
  phylum_sym <- rlang::ensym(phylum_col)
  genome_sym <- rlang::ensym(genome_col)

  # Compute median and 95% interval per tree tip group
  plot_df <- summary_data %>%
    filter(.data[[rlang::as_string(genome_sym)]] %in% tip_order) %>%
    mutate(y_plot = factor(.data[[rlang::as_string(genome_sym)]], levels = tip_order)) %>%
    group_by(y_plot, !!phylum_sym) %>%
    summarise(
      median = median(!!var_sym, na.rm = TRUE),
      p2.5 = quantile(!!var_sym, 0.025, na.rm = TRUE),
      p97.5 = quantile(!!var_sym, 0.975, na.rm = TRUE),
      .groups = "drop"
    )

  # Determine phylum boundaries to draw separators and phylum labels
  phylum_bounds <- plot_df %>%
    group_by(!!phylum_sym) %>%
    summarise(
      top = min(as.numeric(y_plot)),
      bottom = max(as.numeric(y_plot)),
      label_genome = y_plot[which.min(as.numeric(y_plot))],
      .groups = "drop"
    )

  # Build interval + median panel
  p <- ggplot(plot_df, aes(y = y_plot)) +
    geom_linerange(aes(xmin = p2.5, xmax = p97.5), linewidth = 1, color = line_color) +
    geom_point(aes(x = median), size = 2, color = dot_color) +
    labs(x = rlang::as_label(var_sym), y = NULL) +
    theme_minimal(base_size = 10) +
    theme(
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_text(color = "black"),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.75)
    )

  # Add dotted horizontal separators between phyla
  if (nrow(phylum_bounds) > 1) {
    for (i in seq_len(nrow(phylum_bounds) - 1)) {
      p <- p + geom_hline(yintercept = phylum_bounds$bottom[i] + 0.5, linetype = "dotted", color = "gray40")
    }
  }

  # Add phylum labels at the top-most tip position for each phylum
  p <- p + geom_text(
    data = phylum_bounds,
    aes(x = 50, y = top, label = !!phylum_sym),
    hjust = -0.1,
    vjust = 0.5,
    size = 3,
    fontface = "bold",
    inherit.aes = FALSE
  )

  p
}

# -----------------------------------------------------------------------------
# 4) Generate and save Figure 6A panel
# -----------------------------------------------------------------------------

if (!dir.exists("results/figure6")) {
  dir.create("results/figure6", recursive = TRUE)
}

message("Generating signalp_cgc_iqr_plot...")
# Tip order from plotted tree coordinates (used to keep y-axis alignment exact)
tip_order <- family_tree_plot$data %>%
  filter(isTip) %>%
  arrange(y) %>%
  pull(label)

# Percentile panel for n_CGCs_signalp across families
signalp_cgc_iqr <- make_percentile_plot(plot_data, n_CGCs_signalp, tip_order)
# Combined tree + percentile plot object for export
signalp_cgc_iqr_plot <- signalp_cgc_iqr %>% insert_left(family_tree_plot, width = 0.75)

ggsave(
  "results/figure6/Fig6B.pdf",
  signalp_cgc_iqr_plot,
  width = 6,
  height = 9
)

message("Saved: results/figure6/Fig6B.pdf")
