#!/usr/bin/env Rscript

# -----------------------------------------------------------------------------
# Figure 6C plotting script
#
# Purpose:
# Recreate the distribution of patient-level median relative abundance for
# selected Bacteroidota families after quinolone prophylaxis.
#
# Input:
# - data/figure6/bsi_model_input.csv (generated by 00_generate_bsi_model_input.R)
#
# Output:
# - results/figure6/Fig6C.pdf
# -----------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
})

# -----------------------------------------------------------------------------
# 1) Ensure required directories / input table
# -----------------------------------------------------------------------------

if (!dir.exists("results/figure6")) {
  dir.create("results/figure6", recursive = TRUE)
}

if (!file.exists("data/figure6/bsi_model_input.csv")) {
  source("figure6_scripts/00_generate_bsi_model_input.R")
}

# -----------------------------------------------------------------------------
# 2) Plot styling and data loading
# -----------------------------------------------------------------------------

custom_theme <- theme(
  panel.grid = element_blank(),
  panel.background = element_blank(),
  panel.border = element_rect(color = "black", fill = NA, linewidth = 0.75),
  axis.text = element_text(color = "black", size = 10)
)

message("Loading analysis table...")
# Sole analysis input table generated by script 04 (sample-level features).
plot_input <- suppressMessages(read_csv("data/figure6/bsi_model_input.csv"))

# Families of interest highlighted in the original Bacteroidota-family section.
target_families <- c(
  "Bacteroidaceae",
  "Barnesiellaceae",
  "Dysgonomonadaceae",
  "Marinifilaceae",
  "Rikenellaceae",
  "Tannerellaceae",
  "Prevotellaceae"
)

# -----------------------------------------------------------------------------
# 3) Classify samples as pre/post prophylaxis and compute patient medians
# -----------------------------------------------------------------------------

# Quinolone criterion shared with the qmd workflow:
# first quinolone day is defined in the [-10, 0] window and stored as first_quin_day.
# tbl_prevalence keeps all samples with an explicit pre/post prophylaxis label.
tbl_prevalence <- plot_input %>%
  mutate(
    prophylaxis_status = case_when(
      is.na(first_quin_day) ~ "pre", # never received quinolones in window
      DayRelativeToNearestHCT < first_quin_day ~ "pre",
      DayRelativeToNearestHCT >= (first_quin_day + 1) ~ "post",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(prophylaxis_status), prophylaxis_status %in% c("pre", "post"))

# Patient-level medians for each family using post-prophylaxis samples.
# This reproduces the per-patient summary used for the Fig6C box/jitter plot.
patient_medians <- tbl_prevalence %>%
  filter(prophylaxis_status == "post") %>%
  select(PatientID, all_of(paste0(target_families, "_abund"))) %>%
  pivot_longer(
    cols = ends_with("_abund"),
    names_to = "family",
    values_to = "abundance"
  ) %>%
  mutate(family = str_remove(family, "_abund$")) %>%
  group_by(PatientID, family) %>%
  summarise(median_abundance = median(abundance, na.rm = TRUE), .groups = "drop")

# -----------------------------------------------------------------------------
# 4) Build and save Figure 6C
# -----------------------------------------------------------------------------

message("Generating Fig6C...")

# Final Figure 6C object: distribution of patient median abundances by family.
bacteroidota_fam_abund <- ggplot(
  patient_medians,
  aes(
    x = factor(
      family,
      levels = c(
        "Bacteroidaceae", "Tannerellaceae", "Prevotellaceae",
        "Rikenellaceae", "Barnesiellaceae", "Marinifilaceae", "Dysgonomonadaceae"
      )
    ),
    y = log10(median_abundance + 1e-5)
  )
) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, fill = "gray75") +
  geom_jitter(width = 0.2, alpha = 0.2, color = "gray20") +
  labs(
    x = "Family",
    y = "log10(median relative abundance per patient)"
  ) +
  custom_theme +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave("results/figure6/Fig6C.pdf", bacteroidota_fam_abund, width = 9, height = 5)

message("Saved: results/figure6/Fig6C.pdf")
